In [2]:
alist = [1,2,3,4,5,6,7]
emptyList = []
for a in alist:
    emptyList.append(a*2)

In [3]:
emptyList

[2, 4, 6, 8, 10, 12, 14]

In [7]:
import numpy as np
alist = np.array([2,3,4,5,7])

In [8]:
alist*2

array([ 4,  6,  8, 10, 14])

In [10]:
v1= [1,3,4]

In [11]:
type(v1)

list

In [12]:
v1=np.array(v1)

In [13]:
type(v1)

numpy.ndarray

In [14]:
a = np.arange(10)

In [15]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
l1 = [1,2,5]
l2 = [3,4,9] 
l1 = np.array(l1)
l2 = np.array(l2)


l3 = l1 * l2

In [23]:
l3

array([ 3,  8, 45])

In [24]:
l3.ndim

1

In [25]:
np.array([5]).ndim

1

In [26]:
np.array(5).ndim

0

In [27]:
d2 = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [29]:
d2

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [30]:
d2.ndim

2

In [34]:
dd2 = np.array([0,8,9,7])
dd2.ndim

1

In [35]:
dd3 = np.array([[0,8,9,7]])
dd3.ndim

2

In [36]:
dd4 = np.array([[[[[[[[[12]]]]]]]]])
dd4.ndim

9

In [37]:
d2array =np.arange(100).reshape(10,10)

In [38]:
d2array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [41]:
vector = d2array.reshape(100)

In [42]:
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
a1= np.arange(25).reshape(5,5)

In [71]:
a2 = np.arange(25,50).reshape(5,5)

In [66]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
a2

array([[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [68]:
a1.shape

(5, 5)

In [69]:
a2.shape

(1, 25)

In [72]:
a1*a2   #elementwise multiplication

array([[   0,   26,   54,   84,  116],
       [ 150,  186,  224,  264,  306],
       [ 350,  396,  444,  494,  546],
       [ 600,  656,  714,  774,  836],
       [ 900,  966, 1034, 1104, 1176]])

In [74]:
b1 = np.arange(16).reshape(4,4)
b1.shape

(4, 4)

In [75]:
b2 = np.arange(20).reshape(5,4)
b2.shape

(5, 4)

In [76]:
b2@b1

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506],
       [440, 510, 580, 650]])

In [77]:
np.dot(b2,b1)

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506],
       [440, 510, 580, 650]])

In [104]:
q = b2.dot(b1)

In [83]:
matrix = np.array([[1,2,3], [3,4,5]])

In [84]:
matrix

array([[1, 2, 3],
       [3, 4, 5]])

In [86]:
matrix.size

6

In [ ]:
np.size(matrix, 1)

In [91]:
np.zeros(100).reshape(10,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [92]:
np.ones(100).reshape(10,10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [97]:
np.eye(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [103]:
np.linspace(0,140, 91)

array([  0.        ,   1.55555556,   3.11111111,   4.66666667,
         6.22222222,   7.77777778,   9.33333333,  10.88888889,
        12.44444444,  14.        ,  15.55555556,  17.11111111,
        18.66666667,  20.22222222,  21.77777778,  23.33333333,
        24.88888889,  26.44444444,  28.        ,  29.55555556,
        31.11111111,  32.66666667,  34.22222222,  35.77777778,
        37.33333333,  38.88888889,  40.44444444,  42.        ,
        43.55555556,  45.11111111,  46.66666667,  48.22222222,
        49.77777778,  51.33333333,  52.88888889,  54.44444444,
        56.        ,  57.55555556,  59.11111111,  60.66666667,
        62.22222222,  63.77777778,  65.33333333,  66.88888889,
        68.44444444,  70.        ,  71.55555556,  73.11111111,
        74.66666667,  76.22222222,  77.77777778,  79.33333333,
        80.88888889,  82.44444444,  84.        ,  85.55555556,
        87.11111111,  88.66666667,  90.22222222,  91.77777778,
        93.33333333,  94.88888889,  96.44444444,  98.  

In [105]:
q

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506],
       [440, 510, 580, 650]])

In [108]:
ones = (np.ones(100).reshape(10,10))

In [109]:
ones *10

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [111]:
q

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506],
       [440, 510, 580, 650]])

In [112]:
q[1,1]

174

In [115]:
q[1:3,1:3]


array([[174, 196],
       [286, 324]])